[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The AI Writing Professor: Collaborative Learning Strategies and Personalized Feedback for Better Writing Outcomes"
